### ISSUE TITLE
xtls-rprx-vision,none 好像没加上去？

### ISSUE THREAD

**Issue by ZenixYang** [XgHao/ProxySU#3]

**Comment by XgHao** [comment]
https://github.com/XgHao/ProxySU/releases/tag/v4.3.2
最新的版本是支持的。
是选了`xtls-rprx-vision,none`没有生效吗？

**Comment by ZenixYang** [comment]
谢谢，发觉是我选错协议了。 确实有 xtls-rprx-vision,none
