### ISSUE TITLE
VLESS-XTLS-uTLS-REALITY 支持

### ISSUE THREAD

**Issue by wekingchen** [XgHao/ProxySU#4]
能否加入最新的VLESS-XTLS-uTLS-REALITY

**Comment by XgHao** [comment]
最近工作比较忙  有时间 我会加入的

**Comment by wekingchen** [comment]
谢谢

**Comment by tmnt2009** [comment]
同样求加入REALITY协议

**Comment by wekingchen** [comment]
大佬这个项目已经凉了吗？

**Comment by XgHao** [comment]
> 大佬这个项目已经凉了吗？

维护意义已经不大了  很多一键脚本 比这效率高太多了 还有网页后台 一劳永逸 手机上也能改配置
比如3x-ui
https://github.com/MHSanaei/3x-ui/blob/main/README.zh.md

**Comment by wekingchen** [comment]
好的，我研究一下这个，谢谢大佬~

**Comment by XgHao** [comment]
> 好的，我研究一下这个，谢谢大佬~

可以试一下  使用起来比这个简单多了  
不需要里安装什么其他软件
只需要ssh登录到主机 复制一行命令回车 就完成了安装
